<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BusinessManagement.Domain\BusinessManagement.Domain.csproj" />
    <ProjectReference Include="..\BusinessManagement.Shared\BusinessManagement.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.4" />
    <PackageReference Include="EPPlus" Version="7.0.0" />
  </ItemGroup>
</Project>
